#!/bin/bash

set -e

source $(dirname $0)/version

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}}
REPO=${REPO:-rancher}

cp ../bin/docker-longhorn-driver .
docker build -t ${REPO}/docker-longhorn-driver:${TAG} .

echo Built ${REPO}/docker-longhorn-driver:${TAG}


